Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1777
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 48, in login_view
    return redirect('home')
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"POST /users/login/ HTTP/1.1" 500 86358
Not Found: /
"GET / HTTP/1.1" 404 2461
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1777
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 48, in login_view
    return redirect('home')
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"POST /users/login/ HTTP/1.1" 500 84305
"GET /users/login/?next=/users/ HTTP/1.1" 200 1777
"GET /users/login/?next=/users/ HTTP/1.1" 200 1777
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 48, in login_view
    return redirect('home')
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"POST /users/login/ HTTP/1.1" 500 86358
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /users/login/
"POST /users/login/ HTTP/1.1" 403 2503
"GET /users/login/ HTTP/1.1" 200 1777
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 48, in login_view
    return redirect('user')
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
"POST /users/login/ HTTP/1.1" 500 86345
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/login/ HTTP/1.1" 200 1777
"GET /users/login/ HTTP/1.1" 200 1777
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1011
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 7747x 

C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2512
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1777
"GET /static/chipin/styles.css HTTP/1.1" 304 0
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1007
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login'))
                    ~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73720
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login'))
                    ~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73825
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login'))
                    ~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73841
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login'))
                    ~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73841
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login/'))
                    ~~~~~~~^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login/' not found. 'login/' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73859
"GET /users/ HTTP/1.1" 200 1005
"GET /static/chipin/styles.css HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2512
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login/'))
                    ~~~~~~~^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login/' not found. 'login/' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73738
"GET /users/delete/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/users/delete/ HTTP/1.1" 404 2544
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login'))
                    ~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73825
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login/'))
                    ~~~~~~~^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login/' not found. 'login/' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73859
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 2195
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1005
Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 59, in logout_view
    return redirect(reverse('login'))
                    ~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /users/logout/ HTTP/1.1" 500 73720
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1979
"GET /users/register/ HTTP/1.1" 200 2607
"GET /users/login/ HTTP/1.1" 200 1777
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1005
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1907
"GET /users/register/ HTTP/1.1" 200 2607
"GET /users/login/ HTTP/1.1" 200 1777
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1005
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1907
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1009
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1907
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1007
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1907
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1005
"GET /chipin/ HTTP/1.1" 200 1590
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1907
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1005
"GET /chipin/ HTTP/1.1" 200 1590
"GET /chipin/group/1/ HTTP/1.1" 200 1310
"GET /chipin/group/1/invite/ HTTP/1.1" 200 1411
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1907
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1005
"GET /chipin/ HTTP/1.1" 200 1590
"GET /chipin/create_group/ HTTP/1.1" 200 1265
"POST /chipin/create_group/ HTTP/1.1" 200 1477
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1907
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
